# Generated by Django 3.0.8 on 2020-10-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('ingredients', models.CharField(default='', max_length=500)),
                ('instructions', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
