# Generated by Django 3.0.8 on 2020-10-08 04:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, default=datetime.date(2020, 10, 8))),
                ('added_date', models.DateField(default=datetime.date(2020, 10, 8))),
                ('total_cost', models.FloatField(blank=True, default=0)),
                ('purchase_icc', models.CharField(max_length=100)),
                ('num_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('added_date', models.DateField(default=datetime.date(2020, 10, 8))),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.FloatField(blank=True, default=0)),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_items', models.IntegerField(blank=True, default=0, null=True)),
                ('is_empty', models.BooleanField(default=1)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
