# Generated by Django 3.0.8 on 2020-10-18 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='... Who am I? What am I?!', max_length=100)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('prep_time_hours', models.FloatField(blank=True, default=1)),
                ('cook_time_hours', models.FloatField(blank=True, default=1)),
                ('num_serves', models.FloatField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='', max_length=100)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.FloatField(blank=True, default=0)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Inventory')),
                ('recipe_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Recipe')),
            ],
            options={
                'ordering': ['item_name', 'expiry_date'],
            },
        ),
    ]
