# Generated by Django 3.0.8 on 2020-10-18 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='purchase_icc',
            new_name='purchase_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_date',
            field=models.DateField(default=datetime.date(2020, 10, 18)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='added_date',
            field=models.DateField(default=datetime.date(2020, 10, 18)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 18)),
        ),
    ]
