# Generated by Django 3.0.8 on 2020-10-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201018_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
