# Generated by Django 3.0.8 on 2020-10-18 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_delete_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='num_items',
            new_name='num_ingredients',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='num_items',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='purchase_location',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time_hours',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingrediant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='num_serves',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_hours',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
