# Generated by Django 3.0.8 on 2020-10-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201018_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingrediant_id',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='num_ingredients',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cost',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
