# Generated by Django 3.0.8 on 2020-10-18 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201018_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='num_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, default='... Who am I? What am I?!', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 18, 7, 41, 45, 714532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 18, 7, 41, 45, 715530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingrediant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
