# Generated by Django 3.0.8 on 2020-10-18 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201018_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
