# Generated by Django 3.0.8 on 2020-10-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201018_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_id',
            field=models.ManyToManyField(to='inventory.Item'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingrediant_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingrediant_id',
            field=models.ManyToManyField(to='inventory.Item'),
        ),
    ]
